# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/atfie/IceCube/artyS7/vivado_project/artyS7.srcs/sources_1/ip/XDOM_DDR3_PG/XDOM_DDR3_PG.xci
# IP: The module: 'XDOM_DDR3_PG' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/atfie/IceCube/artyS7/vivado_project/artyS7.srcs/sources_1/ip/XDOM_DDR3_PG/XDOM_DDR3_PG_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'XDOM_DDR3_PG'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/atfie/IceCube/artyS7/vivado_project/artyS7.srcs/sources_1/ip/XDOM_DDR3_PG/XDOM_DDR3_PG.xci
# IP: The module: 'XDOM_DDR3_PG' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/atfie/IceCube/artyS7/vivado_project/artyS7.srcs/sources_1/ip/XDOM_DDR3_PG/XDOM_DDR3_PG_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'XDOM_DDR3_PG'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
