# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# IP: C:/Users/atfie/IceCube/artyS7/IPCORES/DPRAM_2048_16/DPRAM_2048_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DPRAM_2048_16 || ORIG_REF_NAME==DPRAM_2048_16} -quiet] -quiet
