set_property PACKAGE_PIN J15 [get_ports {TRICOLOR_LED[5]}]
set_property PACKAGE_PIN G17 [get_ports {TRICOLOR_LED[4]}]
set_property PACKAGE_PIN F15 [get_ports {TRICOLOR_LED[3]}]
set_property PACKAGE_PIN E15 [get_ports {TRICOLOR_LED[2]}]
set_property PACKAGE_PIN F18 [get_ports {TRICOLOR_LED[1]}]
set_property PACKAGE_PIN E14 [get_ports {TRICOLOR_LED[0]}]
set_property PACKAGE_PIN E18 [get_ports {GREEN_LED[3]}]
set_property PACKAGE_PIN F13 [get_ports {GREEN_LED[2]}]
set_property PACKAGE_PIN E13 [get_ports {GREEN_LED[1]}]
set_property PACKAGE_PIN H15 [get_ports {GREEN_LED[0]}]
set_property PACKAGE_PIN F14 [get_ports OSC_12MHZ]
set_property IOSTANDARD LVCMOS33 [get_ports {TRICOLOR_LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TRICOLOR_LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TRICOLOR_LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TRICOLOR_LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TRICOLOR_LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TRICOLOR_LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN_LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN_LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN_LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN_LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports OSC_12MHZ]

set_property IOSTANDARD LVCMOS33 [get_ports UART_RXD]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TXD]
set_property PACKAGE_PIN R12 [get_ports UART_RXD]
set_property PACKAGE_PIN V12 [get_ports UART_TXD]

create_clock -period 83.333 -name OSC_12MHZ -waveform {0.000 41.667} [get_ports OSC_12MHZ]

set_false_path -from [get_clocks -of_objects [get_pins lclk_mmcm_0/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins DDR3_TRANSFER_0/MIG_7_SERIES/u_mig_7series_0_mig/u_ddr3_infrastructure/plle2_i/CLKOUT3]]

set_false_path -from [get_clocks -of_objects [get_pins DDR3_TRANSFER_0/MIG_7_SERIES/u_mig_7series_0_mig/u_ddr3_infrastructure/plle2_i/CLKOUT3]] -to [get_clocks -of_objects [get_pins lclk_mmcm_0/inst/mmcm_adv_inst/CLKOUT0]]

set_false_path -from [get_clocks -of_objects [get_pins lclk_mmcm_0/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins DDR3_TRANSFER_0/MIG_7_SERIES/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]

set_false_path -from [get_clocks -of_objects [get_pins DDR3_TRANSFER_0/MIG_7_SERIES/u_mig_7series_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -to [get_clocks -of_objects [get_pins lclk_mmcm_0/inst/mmcm_adv_inst/CLKOUT0]]